### ISSUE TITLE
Pipeline does not appear in Mage

### ISSUE THREAD

**Issue by tinkermax** [cnstlungu/portable-data-stack-mage#2]
I believe you may have accidentally deleted /mage/pipelines/grateful_flower/metadata.yaml which means that the "grateful flower" pipeline does not appear in Mage after running docker-compose.

Otherwise, thanks for this work!

**Comment by cnstlungu** [comment]
Thanks @tinkermax! You were right. Restored the file.

Things should look better now.

![image](https://github.com/cnstlungu/portable-data-stack-mage/assets/10930578/e81ae12b-cf18-4417-9996-0caa604e4a6e)
